[miio] add alert on miio channels changing
openhab/openhab-distro pull request #1247
Opened 2021-01-13 22:49 UTC by marcelrv

related to  ao https://github.com/openhab/openhab-addons/pull/9756 and https://github.com/openhab/openhab-addons/pull/9384

Signed-off-by: Marcel Verpaalen <marcel@verpaalen.com>

2021-01-14 07:39 UTC, kaikreuzer requested changes
Question: Is this really a breaking change?
It should always be possible to link a dimensionless item to such a channel, so ideally this should be backward compatible.

2021-01-14 07:39 UTC, kaikreuzer commented on distributions/openhab/src/main/resources/bin/update.lst
> +ALERT;Xiaomi MiIo binding: With 3.1 release many channels have been converted from Number to a quanityType number. e.g. temperature channels have been changed from Number to Number:Temperature. You n
```suggestion
ALERT;Xiaomi MiIo Binding: Many channels have been converted from Number to a Number with dimension, e.g. temperature channels have been changed from Number to Number:Temperature. Please see the binding documentation for details.
```

2021-01-14 14:39 UTC, marcelrv commented
> Question: Is this really a breaking change?
> It should always be possible to link a dimensionless item to such a channel, so ideally this should be backward compatible.

To be honest I'm still not 100% clear indeed if it is breaking or not. I recall I had some issues with rules after the change overs.
Nevertheless, I'm very fine with the rewording you did.

2021-02-10 16:31 UTC, kaikreuzer requested changes

2021-02-10 16:31 UTC, kaikreuzer commented on distributions/openhab/src/main/resources/bin/update.lst
> +[3.1.0]
I'd think this sections needs to be moved to https://github.com/openhab/openhab-distro/pull/1247/files#diff-8be360a52adcae6cc237c7d0e4658b2d50028192596d6489f64ee61e4d43f4aaR40, i.e. under `[[MSG]]` and not under `[[PRE]]`.

2021-02-27 20:22 UTC, kaikreuzer approved these changes
Thanks!

2021-02-27 20:23 UTC, merged