Added a note about removal of DarkSky binding due to EOL of their API
openhab/openhab-distro pull request #1404
Opened 2022-06-29 10:38 UTC by cweitkamp

- Added a note about removal of DarkSky binding due to EOL of their API

Signed-off-by: Christoph Weitkamp <github@christophweitkamp.de>

2022-07-16 09:25 UTC, wborn commented
Depends on https://github.com/openhab/openhab-addons/pull/13037

2022-12-21 16:36 UTC, wborn requested changes
Now that the other PR got merged, can you rebase this one and add it to a `[4.0.0]` section?

2022-12-21 17:10 UTC, wborn commented on distributions/openhab/src/main/resources/bin/update.lst
> +ALERT;Dark Sky: Due to EOL of their API, this add-on has been removed.
There's still a merge conflict. 

Adding "Binding" would also be nice:

```suggestion
ALERT;Dark Sky Binding: Due to EOL of their API, this add-on has been removed.
```

2022-12-30 13:11 UTC, cweitkamp commented
> There's still a merge conflict.

Sry, didn't notice. Looks like you already rebased and applied your comment. Thanks.

2022-12-30 13:52 UTC, wborn approved these changes
👍

2022-12-30 13:53 UTC, merged