Add breaking change alert for EspMilightHub
openhab/openhab-distro pull request #1463
Opened 2023-01-15 21:14 UTC by ccutrer

See https://github.com/openhab/openhab-addons/pull/13801

2023-08-04 05:25 UTC, wborn requested changes
It should be moved to the right OH version when it gets merged.

2023-12-16 08:52 UTC, lolodomo commented
@ccutrer : is there something else to change here ? Can you remove the draft status so that it can be merged ?

2023-12-16 18:35 UTC, ccutrer commented
Rebased and put into the proper section. Ready to merge now.

2023-12-16 18:38 UTC, lolodomo commented on distributions/openhab/src/main/resources/bin/update.lst
> +ALERT;MQTT EspMilightHub Binding: Colour bulbs no longer have a `level` channel. You may need to re-add your things for it to be removed. Link to the `colour` channel instead, even for `Dimmer` items
We try to present them in alphabetic order.
Please move up your line.
And if you do it also for Porcupine and Action Template Interpreter, that would be great.

2023-12-16 19:58 UTC, wborn approved these changes
Thanks!

2023-12-16 19:58 UTC, merged