Add entry in update.lst for latest guntamatic binding changes
openhab/openhab-distro pull request #1708
Opened 2024-12-18 11:32 UTC by MikeTheTux

Add entry in update.lst for latest guntamatic binding changes

openhab/openhab-addons#17901

2024-12-20 21:10 UTC, lsiepel commented
Related PR is merged

2024-12-20 21:13 UTC, lsiepel commented on distributions/openhab/src/main/resources/bin/update.lst
> +ALERT;Guntamatic Binding: The Binding now uses channel groups and the dynamic status channels now have an index prefix to allow multiple channels with the same description. Re-connect changed and new
```suggestion
ALERT;Guntamatic Binding: The Binding now uses channel groups and the dynamic status channels now have an index prefix to allow multiple channels with the same description. Existing Items will need to be adjusted.
```

2024-12-21 08:09 UTC, lsiepel approved these changes

2024-12-21 09:28 UTC, holgerfriedrich approved these changes

2024-12-21 09:28 UTC, holgerfriedrich approved these changes
LGTM, thanks!

2024-12-21 09:58 UTC, holgerfriedrich requested changes
@MikeTheTux could you pls. change the signoff (real-name policy)? I think you have done this for the commit in add-ons repo. Thanks!

2024-12-21 11:53 UTC, holgerfriedrich approved these changes
Don't mind, lets consider this as a small patch, not requiring this.

2024-12-21 11:53 UTC, merged